### ISSUE TITLE
 Please add RSS feed plugin

### ISSUE THREAD

**Issue by nitinthewiz** [flexdinesh/flexdinesh.github.io#5]
Hey Dinesh,

I found Awesome Personal blogs and realized there's no RSS feed list (OPML file) in the repo, so I'm adding one. I noticed that your blog doesn't have an RSS feed, simply because you've not added the gatsby feed plugin to it.

I found that the way to do it is pretty simple - https://github.com/gatsbyjs/gatsby-starter-blog/search?q=feed&unscoped_q=feed

Could you please add a feed and then update the OPML file? (I've not submitted it yet to the awesome personal blogs repo, will do it soon)

**Comment by flexdinesh** [comment]
Thanks Nithin. I will add the plugin in a day or two and update it here.

**Comment by flexdinesh** [comment]
@nitinthewiz I have added the rss feed plugin now. You can now find the feed at 

https://dineshpandiyan.com/rss.xml

**Comment by nitinthewiz** [comment]
Awesome! 👍
